language: go
sudo: false
go:
  - '1.14'
  - '1.15'
  - '1.16'
  - '1.17'
  - '1.18'
  - 'tip'

services:
  - mongodb

before_install:
  - mkdir -p $GOPATH/bin $GOPATH/pkg $GOPATH/src
  - go install github.com/mattn/goveralls

install:
  - go get

script:
  - go test -v ./... -covermode=count -coverprofile=coverage.out
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

