name: go
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.18' ] # '1.13', '1.14', '1.15', '1.16', '1.17',
        mongo: [ '4.4' ] # '4.2', '5.0'

    name: Go ${{ matrix.go }} with MongoDB ${{ matrix.mongo }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongo }}

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Go Test
        run: |
          go version
          go test -v .\...
